# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import json
import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.gemini335l.configuration_gemini335l import Gemini335LCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
    zionnerP1_follower,
)
from lerobot.robots.zionnerP1_follower import ZIONNER_P1_JOINTS
from lerobot.robots.vendor.xcore_sdk import XCoreZionnerP1Client
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
    zionnerP1_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, HF_LEROBOT_HOME, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_devices
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


REPLAY_START_ALIGN_TIMEOUT_S = 5.0
REPLAY_START_ALIGN_TOLERANCE_RAD = 0.03
REPLAY_START_ALIGN_STEP_RAD = 0.01


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class WorkflowConfig:
    mode: str = "normal"
    trajectory_json_path: str | Path | None = None
    teach_power_off: bool = True


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    workflow: WorkflowConfig = field(default_factory=WorkflowConfig)
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.workflow.mode == "normal" and self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

        if self.workflow.mode not in {"normal", "teach", "replay_record"}:
            raise ValueError(
                "workflow.mode must be one of {'normal', 'teach', 'replay_record'}"
            )

        if self.workflow.mode in {"teach", "replay_record"}:
            if self.robot.type != "zionnerP1_follower":
                raise ValueError(
                    "workflow.mode=teach/replay_record currently only supports "
                    "robot.type=zionnerP1_follower"
                )
            if self.teleop is not None or self.policy is not None:
                raise ValueError(
                    "workflow.mode=teach/replay_record does not use teleop or policy. "
                    "Leave both unset."
                )

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so100_leader.SO100Leader
                        | so101_leader.SO101Leader
                        | zionnerP1_leader.ZionnerP1Leader
                        | koch_leader.KochLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=obs_processed, action=action_values)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


def teach_loop(
    client: XCoreZionnerP1Client,
    events: dict,
    fps: int,
    control_time_s: int | float | None,
) -> list[dict[str, Any]]:
    timestamp = 0.0
    start_episode_t = time.perf_counter()
    frames: list[dict[str, Any]] = []

    while control_time_s is None or timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        joint_positions = client.read_joint_positions()
        frames.append(
            {
                "timestamp": timestamp,
                "joints": [float(value) for value in joint_positions],
            }
        )

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)
        timestamp = time.perf_counter() - start_episode_t

    return frames


def replay_record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],
    trajectory_frames: list[dict[str, Any]],
    dataset: LeRobotDataset | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    episode_index: int | None = None,
    control_time_s: int | float | None = None,
) -> dict[str, float | int]:
    if not trajectory_frames:
        return {
            "frames": 0,
            "total_observation_s": 0.0,
            "total_action_s": 0.0,
            "total_add_frame_s": 0.0,
            "total_loop_s": 0.0,
            "max_observation_s": 0.0,
            "max_action_s": 0.0,
            "max_loop_s": 0.0,
            "trajectory_duration_s": 0.0,
            "target_duration_s": 0.0,
            "last_source_frame_index": 0,
            "start_align_s": 0.0,
            "start_align_iterations": 0,
            "start_align_initial_max_abs_error": 0.0,
            "start_align_final_max_abs_error": 0.0,
            "start_aligned": 1,
        }

    trajectory_timestamps = [
        float(frame.get("timestamp", index / fps))
        for index, frame in enumerate(trajectory_frames)
    ]
    trajectory_duration_s = (
        trajectory_timestamps[-1] if trajectory_timestamps else 0.0
    )
    target_duration_s = trajectory_duration_s
    if control_time_s is not None:
        target_duration_s = min(target_duration_s, float(control_time_s))

    total_frames = 0
    total_observation_s = 0.0
    total_action_s = 0.0
    total_add_frame_s = 0.0
    total_loop_s = 0.0
    max_observation_s = 0.0
    max_action_s = 0.0
    max_loop_s = 0.0
    selected_frame_index = 0
    max_source_frame_index = 0
    first_action = {
        joint_name: float(value)
        for joint_name, value in zip(
            ZIONNER_P1_JOINTS,
            trajectory_frames[0]["joints"],
            strict=True,
        )
    }
    start_align_t = time.perf_counter()
    start_align_iterations = 0
    current_joint_positions = {
        joint_name: float(value)
        for joint_name, value in zip(
            ZIONNER_P1_JOINTS,
            robot.client.read_joint_positions(),
            strict=True,
        )
    }
    initial_max_abs_error = max(
        abs(current_joint_positions[joint_name] - target)
        for joint_name, target in first_action.items()
    )
    final_max_abs_error = initial_max_abs_error
    bridge_steps = max(
        1,
        int(initial_max_abs_error / REPLAY_START_ALIGN_STEP_RAD),
    )
    max_bridge_steps = max(1, int(REPLAY_START_ALIGN_TIMEOUT_S * fps))
    bridge_steps = min(bridge_steps, max_bridge_steps)

    for step_index in range(1, bridge_steps + 1):
        if events["exit_early"] or events["stop_recording"]:
            break

        alpha = step_index / bridge_steps
        bridge_action = {
            joint_name: (
                current_joint_positions[joint_name]
                + alpha
                * (
                    first_action[joint_name]
                    - current_joint_positions[joint_name]
                )
            )
            for joint_name in ZIONNER_P1_JOINTS
        }
        robot_action_to_send = robot_action_processor(
            (bridge_action, current_joint_positions)
        )
        robot.send_action(robot_action_to_send)
        start_align_iterations += 1
        busy_wait(1 / fps)

    aligned_joint_positions = {
        joint_name: float(value)
        for joint_name, value in zip(
            ZIONNER_P1_JOINTS,
            robot.client.read_joint_positions(),
            strict=True,
        )
    }
    final_max_abs_error = max(
        abs(aligned_joint_positions[joint_name] - target)
        for joint_name, target in first_action.items()
    )
    start_aligned = final_max_abs_error <= REPLAY_START_ALIGN_TOLERANCE_RAD
    start_align_duration_s = time.perf_counter() - start_align_t
    start_episode_t = time.perf_counter()

    while trajectory_frames:
        start_loop_t = time.perf_counter()
        elapsed_s = start_loop_t - start_episode_t

        if elapsed_s >= target_duration_s:
            break

        if events["exit_early"]:
            events["exit_early"] = False
            break

        while (
            selected_frame_index + 1 < len(trajectory_frames)
            and trajectory_timestamps[selected_frame_index + 1] <= elapsed_s
        ):
            selected_frame_index += 1

        max_source_frame_index = max(
            max_source_frame_index,
            selected_frame_index,
        )
        trajectory_frame = trajectory_frames[selected_frame_index]

        start_observation_t = time.perf_counter()
        obs = robot.get_observation()
        observation_dt_s = time.perf_counter() - start_observation_t
        obs_processed = robot_observation_processor(obs)
        observation_frame = build_dataset_frame(
            dataset.features,
            obs_processed,
            prefix=OBS_STR,
        )

        action = {
            joint_name: float(value)
            for joint_name, value in zip(
                ZIONNER_P1_JOINTS,
                trajectory_frame["joints"],
                strict=True,
            )
        }
        robot_action_to_send = robot_action_processor((action, obs))
        start_action_t = time.perf_counter()
        sent_action = robot.send_action(robot_action_to_send)
        action_dt_s = time.perf_counter() - start_action_t

        add_frame_dt_s = 0.0
        if dataset is not None:
            start_add_frame_t = time.perf_counter()
            action_frame = build_dataset_frame(
                dataset.features,
                sent_action,
                prefix=ACTION,
            )
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)
            add_frame_dt_s = time.perf_counter() - start_add_frame_t

        if display_data:
            log_rerun_data(observation=obs_processed, action=sent_action)

        dt_s = time.perf_counter() - start_loop_t
        total_frames += 1
        total_observation_s += observation_dt_s
        total_action_s += action_dt_s
        total_add_frame_s += add_frame_dt_s
        total_loop_s += dt_s
        max_observation_s = max(max_observation_s, observation_dt_s)
        max_action_s = max(max_action_s, action_dt_s)
        max_loop_s = max(max_loop_s, dt_s)

        busy_wait(1 / fps - dt_s)

    return {
        "frames": total_frames,
        "total_observation_s": total_observation_s,
        "total_action_s": total_action_s,
        "total_add_frame_s": total_add_frame_s,
        "total_loop_s": total_loop_s,
        "max_observation_s": max_observation_s,
        "max_action_s": max_action_s,
        "max_loop_s": max_loop_s,
        "trajectory_duration_s": trajectory_duration_s,
        "target_duration_s": target_duration_s,
        "last_source_frame_index": max_source_frame_index,
        "start_align_s": start_align_duration_s,
        "start_align_iterations": start_align_iterations,
        "start_align_initial_max_abs_error": initial_max_abs_error,
        "start_align_final_max_abs_error": final_max_abs_error,
        "start_aligned": int(start_aligned),
    }


def passive_wait_loop(events: dict, control_time_s: int | float) -> None:
    start_wait_t = time.perf_counter()
    while time.perf_counter() - start_wait_t < control_time_s:
        if events["exit_early"]:
            events["exit_early"] = False
            break
        busy_wait(0.05)


def get_trajectory_json_path(cfg: RecordConfig) -> Path:
    if cfg.workflow.trajectory_json_path is not None:
        return Path(cfg.workflow.trajectory_json_path)

    dataset_root = (
        Path(cfg.dataset.root)
        if cfg.dataset.root is not None
        else HF_LEROBOT_HOME / cfg.dataset.repo_id
    )
    return dataset_root / "trajectory.json"


def load_trajectory_payload(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def save_trajectory_payload(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False))


def create_empty_trajectory_payload(cfg: RecordConfig) -> dict[str, Any]:
    return {
        "version": 1,
        "robot_type": cfg.robot.type,
        "fps": cfg.dataset.fps,
        "joint_names": list(ZIONNER_P1_JOINTS),
        "single_task": cfg.dataset.single_task,
        "episodes": [],
    }


def set_robot_power_state(
    client: XCoreZionnerP1Client,
    enabled: bool,
) -> None:
    robot = client._require_robot()
    ec: dict[str, Any] = {}
    robot.setPowerState(enabled, ec)
    if ec.get("ec", 0) != 0:
        raise RuntimeError(f"setPowerState({enabled}) failed: {ec}")


def record_teach_trajectory(cfg: RecordConfig) -> Path:
    trajectory_path = get_trajectory_json_path(cfg)
    if cfg.resume:
        if not trajectory_path.exists():
            raise FileNotFoundError(
                f"Trajectory JSON not found for resume: {trajectory_path}"
            )
        payload = load_trajectory_payload(trajectory_path)
    else:
        if trajectory_path.exists():
            raise FileExistsError(
                f"Trajectory JSON already exists: {trajectory_path}. "
                "Use --resume=true or change workflow.trajectory_json_path."
            )
        payload = create_empty_trajectory_payload(cfg)

    client = XCoreZionnerP1Client(
        ip_address=cfg.robot.ip_address,
        local_ip_address=cfg.robot.local_ip_address,
        use_realtime=False,
    )
    listener = None
    recorded_episodes = 0

    try:
        client.connect()
        if cfg.workflow.teach_power_off:
            try:
                set_robot_power_state(client, False)
            except RuntimeError as error:
                logging.warning("Failed to power off robot for teach mode: %s", error)

        listener, events = init_keyboard_listener()

        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            episode_index = len(payload["episodes"])
            log_say(f"Recording episode {episode_index}", cfg.play_sounds)
            frames = teach_loop(
                client=client,
                events=events,
                fps=cfg.dataset.fps,
                control_time_s=cfg.dataset.episode_time_s,
            )

            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1)
                or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                passive_wait_loop(events, cfg.dataset.reset_time_s)

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                continue

            payload["episodes"].append(
                {
                    "episode_index": episode_index,
                    "single_task": cfg.dataset.single_task,
                    "frames": frames,
                }
            )
            save_trajectory_payload(trajectory_path, payload)
            recorded_episodes += 1
    finally:
        client.disconnect()
        if not is_headless() and listener is not None:
            listener.stop()

    log_say("Stop recording", cfg.play_sounds, blocking=True)
    log_say("Exiting", cfg.play_sounds)
    return trajectory_path


def record_replay_dataset(cfg: RecordConfig) -> LeRobotDataset:
    trajectory_path = get_trajectory_json_path(cfg)
    if not trajectory_path.exists():
        raise FileNotFoundError(
            f"Trajectory JSON not found: {trajectory_path}"
        )

    trajectory_payload = load_trajectory_payload(trajectory_path)
    trajectory_fps = int(trajectory_payload["fps"])
    if trajectory_fps != cfg.dataset.fps:
        logging.warning(
            "Trajectory fps (%s) differs from dataset fps (%s). "
            "Replaying at dataset fps.",
            trajectory_fps,
            cfg.dataset.fps,
        )

    robot = make_robot_from_config(cfg.robot)
    _, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=robot_action_processor,
            initial_features=create_initial_features(action=robot.action_features),
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=(
                    cfg.dataset.num_image_writer_threads_per_camera
                    * len(robot.cameras)
                ),
            )
        sanity_check_dataset_robot_compatibility(
            dataset,
            robot,
            cfg.dataset.fps,
            dataset_features,
        )
    else:
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=(
                cfg.dataset.num_image_writer_threads_per_camera
                * len(robot.cameras)
            ),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    start_trajectory_episode = dataset.num_episodes if cfg.resume else 0
    trajectory_episodes = trajectory_payload["episodes"]
    if start_trajectory_episode >= len(trajectory_episodes):
        raise ValueError(
            "No remaining trajectory episodes to replay. "
            f"trajectory_episodes={len(trajectory_episodes)}, "
            f"start_trajectory_episode={start_trajectory_episode}"
        )

    robot.connect()
    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        trajectory_episode_index = start_trajectory_episode
        while (
            recorded_episodes < cfg.dataset.num_episodes
            and trajectory_episode_index < len(trajectory_episodes)
            and not events["stop_recording"]
        ):
            current_episode_index = dataset.num_episodes
            trajectory_episode = trajectory_episodes[trajectory_episode_index]
            log_say(f"Recording episode {current_episode_index}", cfg.play_sounds)
            episode_start_t = time.perf_counter()
            replay_stats = replay_record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                trajectory_frames=trajectory_episode["frames"],
                dataset=dataset,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                episode_index=current_episode_index,
                control_time_s=cfg.dataset.episode_time_s,
            )
            logging.info(
                "Replay episode %s summary: frames=%s wall=%.3fs trajectory_duration=%.3fs target_duration=%.3fs last_source_frame=%s start_align=%.3fs start_align_iterations=%s start_align_initial_max_abs_error=%.3frad start_align_final_max_abs_error=%.3frad start_aligned=%s obs_total=%.3fs action_total=%.3fs add_frame_total=%.3fs max_obs=%.3fs max_action=%.3fs max_loop=%.3fs",
                current_episode_index,
                replay_stats["frames"],
                time.perf_counter() - episode_start_t,
                replay_stats["trajectory_duration_s"],
                replay_stats["target_duration_s"],
                replay_stats["last_source_frame_index"],
                replay_stats["start_align_s"],
                replay_stats["start_align_iterations"],
                replay_stats["start_align_initial_max_abs_error"],
                replay_stats["start_align_final_max_abs_error"],
                replay_stats["start_aligned"],
                replay_stats["total_observation_s"],
                replay_stats["total_action_s"],
                replay_stats["total_add_frame_s"],
                replay_stats["max_observation_s"],
                replay_stats["max_action_s"],
                replay_stats["max_loop_s"],
            )

            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1)
                or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                reset_start_t = time.perf_counter()
                passive_wait_loop(events, cfg.dataset.reset_time_s)
                logging.info(
                    "Replay episode %s reset wait: %.3fs",
                    current_episode_index,
                    time.perf_counter() - reset_start_t,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            save_start_t = time.perf_counter()
            dataset.save_episode()
            logging.info(
                "Replay episode %s save_episode: %.3fs",
                current_episode_index,
                time.perf_counter() - save_start_t,
            )
            recorded_episodes += 1
            trajectory_episode_index += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def record_normal(cfg: RecordConfig) -> LeRobotDataset:
    if cfg.display_data:
        init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
    preprocessor = None
    postprocessor = None
    if cfg.policy is not None:
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            dataset.save_episode()
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.workflow.mode == "teach":
        record_teach_trajectory(cfg)
        return None
    if cfg.workflow.mode == "replay_record":
        return record_replay_dataset(cfg)
    return record_normal(cfg)


def main():
    register_third_party_devices()
    record()


if __name__ == "__main__":
    main()
